### ISSUE TITLE
Battle System: No option to flee/exit ongoing battles

### ISSUE THREAD

**Issue by adamben04** [cse403-fitquest/fitquest#107]
Currently there is no mechanism to exit or flee from an ongoing battle, forcing users to either complete the battle or close/restart the app. This creates a poor user experience, especially if players need to suddenly stop playing or are struggling with a difficult encounter. Need to implement a flee/exit button with appropriate consequences (e.g. loss of some resources) to give players more control over their gameplay experience.

**Comment by afutofu** [comment]
This is a good suggestion. However we don't intend to implement it anytime soon. Will close this issue for that reason.
