### ISSUE TITLE
Friend Request Added Before Email Validation

### ISSUE THREAD

**Issue by adamben04** [cse403-fitquest/fitquest#110]
When sending a friend request, the request shows up in the "Sent Requests" list before validating if the email belongs to an existing user. The request briefly appears and then disappears when the "User not found" error pops up. We should validate the email first before adding anything to the sent requests list to avoid this misleading UI feedback.

**Comment by afutofu** [comment]
Good point. Will work on it

**Comment by adamben04** [comment]
fixed: https://github.com/cse403-fitquest/fitquest/pull/123
