### ISSUE TITLE
Could not build project using instructions for emulating android  

### ISSUE THREAD

**Issue by joshcherndev** [cse403-fitquest/fitquest#78]
Need more steps after part 4 of the project installation guide in the README to explain how to use the emulator to start/build the project. I followed the Expo docs in step 4 and was unclear for a while that I had to install the Expo Go app which is what I did. The code that I am supposed to enter into the app never appears when I execute "npm start". 
![image](https://github.com/user-attachments/assets/8013678a-f77a-4628-addc-e81d7fa7935a)
There were no instructions for downloading the app and receiving code in the setup instructions, I had to figure this out from a teammate who has had experience with using Expo to emulate android in the past. I have a feeling that when I executed "npm install" the packages were not installed properly even though I followed the available instructions.

I would advise a more detailed chain of instructions so that no one feels lost when setting up and so that if errors do pop up when installing packages you can provide troubleshooting steps for when stuff goes wrong, like in my case.

**Comment by afutofu** [comment]
Hu Josh, thanks for the feedback and sorry you had a rough time with the setup. It seems the problem stems from the QR code not properly displaying in the terminal when you run `npm start`. None of our team members experienced this issue so we had no idea this was possible. I did some digging around and a potential fix for this is to ensure that your node version is 20.x LTS, (then reload your developer window if still open,) then delete the `package-lock.json` file and `/node_modules` folder generated from the `npm install` step of the setup. After deleting those, do another npm install and see if you have the QR code in the terminal this time. I also made it clearer in the README which steps you should be using based on what device you have.

**Comment by joshcherndev** [comment]
Hey Afuza,
Thank you for adding these troubleshooting steps. It will hopefully help clear up any confusion for people having trouble like me.

Also change the link for downloading node to link directly to the page for the 20.x LTS version because I accidentally installed the 22.x version: https://nodejs.org/en/download/prebuilt-installer
